import { StyleSheet } from 'react-native';

// All styles used in App.

export const styles = StyleSheet.create({
    container: {      
      //paddingTop: 30,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },

    outer: {      
      // paddingTop: 20,
      flex:1,
      // backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      // borderWidth: 2,
    },
    containerNew: { 
      flexDirection: 'row',  
      justifyContent: 'space-between',   
      // paddingTop: 30,
      flex:1,
      // backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      // borderWidth: 2,
    },
    containerNew2: { 
      flexDirection: 'row',  
      justifyContent: 'space-between',   
      // paddingTop: 30,
      paddingBottom: 30,
      flex:1,
      // backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      // borderWidth: 2,
    },
    SiteContDash: {
      flexDirection: 'column',
      width: '50%',
      justifyContent: 'center',
      alignItems: 'center',
      
      // flexWrap: 'wrap',
      // borderWidth: 2,
    },
    SiteContDashL: {
      flexDirection: 'column',
      padding:20,
      width: '80%',
      justifyContent: 'center',
      alignItems: 'center',
      // flexWrap: 'wrap',
      // borderWidth: 2,
    },
    SiteContDashAv: {
      flexDirection: 'column',
      padding:0,
      width: '60%',
      justifyContent: 'center',
      alignItems: 'center',
      // flexWrap: 'wrap',
      // borderWidth: 2,
    },
    SiteContDashR: {
      flexDirection: 'column',
      width: '30%',
      justifyContent: 'center',
      alignItems: 'center',
      position:'absolute',
      top: 170,
      left: 238,
      // flexWrap: 'wrap',
      // borderWidth: 2,
    },
    searchLoc: {
      paddingTop: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    input: {
      paddingTop: 0,
      width: '95%',
      // padding: 8,
      // margin: 10,
      // borderWidth: 1,
      borderBottomColor: 'black',
      borderBottomWidth: 1,
    },
    big: {
      fontSize:48,
      padding: 40,
      textAlign: "center",
    },
    heading: {
      height:'10%',
      alignItems: 'center',
      paddingTop: 30,
      fontSize: 48,
    },
    headingText: {
      alignItems: 'center',
      fontSize: 48,
      textAlignVertical: 'top',
      fontWeight: "bold",
    },
    info: {
      height: '100%',
      backgroundColor: '#fff',
      fontSize: 20,
      padding: 10,
      fontWeight: "bold",
      textAlign: "center",
    },
    infoAddress: {
      fontSize: 20,
      padding: 10,
      textAlign: "center",
    },
    updated: {
      fontSize: 14,
      padding: 5,
      fontWeight: "bold",
      textAlign: "center",
    },
    updated2: {
      fontSize: 30,
      padding: 10,
      paddingTop: 25,
      fontWeight: "bold",
      textAlign: "center",
    },
    updated3: {
      fontSize: 20,
      padding: 5,
      paddingTop: 25,
      fontWeight: "bold",
      textAlign: "center",
    },
    listItem: {
      flexDirection: 'row',
      //alignItems: 'flex-start',
      backgroundColor: '#fff',
      borderBottomWidth: 1,
      padding: 10,
      justifyContent: 'space-between',
      //flexWrap: 'wrap',
      flex: 1,
      borderColor: '#dcdcdc',
      borderWidth: 8,
    },
    listItem2: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: '#fff',
      borderBottomWidth: 1,
      padding: 20,
      justifyContent: 'space-between',
      //flexWrap: 'wrap',
      // flex: 1,
      borderColor: '#dcdcdc',
      // borderWidth: 2,
    },
    listItemLoc: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: '#fff',
      borderBottomWidth: 1,
      padding: 20,
      justifyContent: 'space-between',
      //flexWrap: 'wrap',
      // flex: 1,
      borderColor: '#dcdcdc',
      // borderWidth: 2,
    },
    listItem3: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      
      backgroundColor: '#fff',
      
      //  padding: 20,
      justifyContent: 'space-between',
      borderColor: 'black',
      // borderWidth: 2,
    },
    listItem3But: {
      height: 100,
      width: "90%",
      borderColor: 'black',
      // borderWidth: 2,
    },
    
    SiteCont: {
      flexDirection: 'column',
      width: '65%',
      justifyContent: 'space-between',
      alignContent: 'space-between',
      //flexWrap: 'wrap',
      // borderWidth: 2,
    },
    SiteCont2: {
      flexDirection: 'column',
      width: '35%',
      justifyContent: 'space-between',
      alignContent: 'space-between',
      // flexWrap: 'wrap',
      // borderWidth: 2,
    },
    SiteText: {
      //height: '50%',
      fontSize: 20,
      padding: 5,
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
      flexWrap: 'wrap',
      width: "100%",
      //fontWeight: "bold",
      //borderWidth: 2,
    },
    SubCont: {
      //height: '50%',
      marginLeft: "1%",
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      // borderWidth: 2,
    },
    SubText: {
      maxWidth:'60%',
      fontSize: 16,
      padding: 5,
      textAlign: "left",
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      // borderWidth: 2,
    },
    SubText2: {
      maxWidth:'100%',
      fontSize: 16,
      padding: 5,
      textAlign: "left",
      // alignItems: 'flex-start',
      justifyContent: 'flex-end',
      // borderWidth: 2,
    },
    doneBit: {
      flexDirection: 'row',
      Width:'20%',
      fontSize: 18,
      paddingRight:25,
      // padding: 15,
      // textAlign: "right",
      alignItems: 'center',
      justifyContent: 'center',
      // borderWidth: 2,
    },
    doneBit2: {
      flexDirection: 'row',
      Width:'90%',
      fontSize: 16,
      padding: 10,
      paddingLeft:135,
      textAlign: "right",
      alignItems: 'flex-end',
      justifyContent: 'flex-end',
      // borderWidth: 2,
    },
    doneBit4: {
      flexDirection: 'row',
      Width:'90%',
      fontSize: 16,
      padding: 10,
      paddingLeft:155,
      textAlign: "right",
      alignItems: 'flex-end',
      justifyContent: 'flex-end',
      // borderWidth: 2,
    },
    doneBitTX: {
      fontSize: 16,
      padding: 15,
      paddingRight:20,
      textAlign: "right",
      alignItems: 'center',
      justifyContent: 'center',
      // borderWidth: 2,
    },
    selectOption: {
      padding: 10,
      fontSize: 18,
      textAlign: "right",
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      // borderWidth: 2,
      borderRadius: 40,
    },
    recentText: {
      fontSize: 14,
      padding: 10,
      fontWeight: "bold",
      textAlign: "left",
      alignItems: 'flex-end',
      justifyContent: 'flex-end',
      //borderWidth: 2,
    },
    infoCont: {
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      alignItems: 'center',
      width: "35%",
      // borderWidth: 2,
    },
    infoCont2: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      width: "65%",
      // borderWidth: 2,
    },
    DistText: {
      fontSize: 16,
      color: 'white',
      fontWeight: "bold",
      textAlign: 'center',
      textAlignVertical: 'center',
      // borderWidth: 2,
      height: 60,
      width: 60,
      borderRadius: 120,
    },
    siteCount: {
      fontSize: 16,
      color: 'white',
      backgroundColor: '#BDC3C7',
      fontWeight: "bold",
      textAlign: 'center',
      textAlignVertical: 'center',
      // borderWidth: 2,
      height: 60,
      width: 60,
      borderRadius: 120,
    },
    RiskView: {
      fontSize: 50,
      color: 'white',
      backgroundColor: '#BDC3C7',
      fontWeight: "bold",
      textAlign: 'center',
      textAlignVertical: 'center',
      // borderWidth: 2,
      height: 160,
      width: 160,
      borderRadius: 320,
    },
    casesView: {
      fontSize: 55,
      color: 'white',
      backgroundColor: '#BDC3C7',
      fontWeight: "bold",
      textAlign: 'center',
      textAlignVertical: 'center',
      // borderWidth: 2,
      height: 210,
      width: 210,
      borderRadius: 420,
    },
    average: {
      fontSize: 49,
      color: 'white',
      backgroundColor: '#BDC3C7',
      fontWeight: "bold",
      textAlign: 'center',
      textAlignVertical: 'center',
      // borderWidth: 2,
      height: 190,
      width: 190,
      borderRadius: 380,
    },
    casesChange: {
      fontSize: 25,
      color: 'white',
      backgroundColor: '#BDC3C7',
      fontWeight: "bold",
      textAlign: 'center',
      textAlignVertical: 'center',
      // borderWidth: 2,
      height: 80,
      width: 80,
      borderRadius: 160,
    },
    separator: {
      marginVertical: 0,
      borderBottomColor: '#737373',
      borderBottomWidth: StyleSheet.hairlineWidth,
    },
  });