import { StyleSheet } from 'react-native';

// All styles used in App.

export const styles = StyleSheet.create({
    container: {      
      //paddingTop: 30,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    containerNew: {      
      paddingTop: 30,
      // backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    searchLoc: {
      paddingTop: 30,
      alignItems: 'center',
      justifyContent: 'center',
    },
    input: {
      // paddingTop: 30,
      width: '60%',
      // padding: 8,
      margin: 10,
      // borderWidth: 1,
      borderBottomColor: 'black',
      borderBottomWidth: 1,
    },
    big: {
      fontSize:48,
      padding: 40,
      textAlign: "center",
    },
    heading: {
      height:'10%',
      alignItems: 'center',
      paddingTop: 30,
      fontSize: 48,
    },
    headingText: {
      alignItems: 'center',
      fontSize: 48,
      textAlignVertical: 'top',
      fontWeight: "bold",
    },
    info: {
      height: '100%',
      backgroundColor: '#fff',
      fontSize: 20,
      padding: 10,
      fontWeight: "bold",
      textAlign: "center",
    },
    infoAddress: {
      fontSize: 20,
      padding: 10,
      textAlign: "center",
    },
    updated: {
      fontSize: 14,
      padding: 5,
      fontWeight: "bold",
      textAlign: "center",
    },
    listItem: {
      flexDirection: 'row',
      //alignItems: 'flex-start',
      backgroundColor: '#fff',
      borderBottomWidth: 1,
      padding: 10,
      justifyContent: 'space-between',
      //flexWrap: 'wrap',
      flex: 1,
      borderColor: '#dcdcdc',
      borderWidth: 8,
    },
    
    SiteCont: {
      flexDirection: 'column',
      width: '65%',
      justifyContent: 'space-between',
      alignContent: 'space-between',
      //flexWrap: 'wrap',
      // borderWidth: 2,
    },
    SiteText: {
      //height: '50%',
      fontSize: 20,
      padding: 5,
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
      flexWrap: 'wrap',
      width: "100%",
      //fontWeight: "bold",
      //borderWidth: 2,
    },
    SubCont: {
      //height: '50%',
      marginLeft: "1%",
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      // borderWidth: 2,
    },
    SubText: {
      maxWidth:'60%',
      fontSize: 16,
      padding: 10,
      textAlign: "left",
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      // borderWidth: 2,
    },
    recentText: {
      fontSize: 14,
      padding: 10,
      fontWeight: "bold",
      textAlign: "left",
      alignItems: 'flex-end',
      justifyContent: 'flex-end',
      //borderWidth: 2,
    },
    infoCont: {
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      alignItems: 'center',
      width: "35%",
      // borderWidth: 2,
    },
    DistText: {
      fontSize: 16,
      color: 'white',
      fontWeight: "bold",
      textAlign: 'center',
      textAlignVertical: 'center',
      // borderWidth: 2,
      height: 60,
      width: 60,
      borderRadius: 120,
    },
    siteCount: {
      fontSize: 16,
      color: 'white',
      backgroundColor: '#BDC3C7',
      fontWeight: "bold",
      textAlign: 'center',
      textAlignVertical: 'center',
      // borderWidth: 2,
      height: 60,
      width: 60,
      borderRadius: 120,
    },
    separator: {
      marginVertical: 0,
      borderBottomColor: '#737373',
      borderBottomWidth: StyleSheet.hairlineWidth,
    },
  });